on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  release:
    types: [published]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt install -y rlwrap python-pip3
        sudo pip install qiskit qiskit-aer --break-system-packages

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@13.4
      with:
        tools-deps: latest

    - name: Run Tests
      run: clj -X:test

  deploy_snapshot:
    name: Deploy Snapshot to Clojars
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: sudo apt install -y rlwrap

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@13.4
      with:
        tools-deps: latest

    - name: Deploy to Clojars
      run: clj -T:build deploy
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}

  deploy_release:
    name: Deploy Release to Clojars
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'release'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: sudo apt install -y rlwrap

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@13.4
      with:
        tools-deps: latest

    - name: Deploy Release to Clojars
      run: clj -T:build deploy
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
          
